### ISSUE TITLE
Adjust .travis.yml for Cake 2.x to include the GitHub ENV PRIVATE_KEY

### ISSUE THREAD

**Issue by jtyost2** [loadsys/CakePHP-Plugin-Skeleton#12]
Ref: https://github.com/FriendsOfCake/travis/issues/59#issuecomment-92382588

**Comment by jtyost2** [comment]
Make very clear the travis key needs to have only `read_only_public_repo` access and that is it.

**Comment by jtyost2** [comment]
Adjust Composer install line to use the GITHUB_TOKEN:

Somewhere in the before_install, probably
`- composer config -g github-oauth.github.com $GITHUB_TOKEN`

**Comment by jtyost2** [comment]
Note the token isn't readonly it's read and write.

https://developer.github.com/v3/oauth/#scopes

Do we still want to enable this change?

**Comment by jtyost2** [comment]
Blahh then again, having more issues related to this now, awesome times: https://travis-ci.org/loadsys/CakePHP-Serializers/jobs/58369175

**Comment by jtyost2** [comment]
Actually it's encrypted via the travis stuff so I don't think it really matters.

**Comment by beporter** [comment]
Well let's call it "minimum permissions" if not "read only". We should only need public repo access and nothing else I think.

**Comment by jtyost2** [comment]
Yeah I agree.

**Comment by ricog** [comment]
Wouldn't `(no scope)` be the read-only scope you are looking for?

On Tue, Apr 14, 2015 at 12:33 AM, Justin Yost <notifications@github.com>
wrote:

> Yeah I agree.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loadsys/CakePHP-Plugin-Skeleton/issues/12#issuecomment-92608816>
> .
>



-- 
Rick Guyer
Project Manager
Loadsys Consulting Inc.
Email: rick@loadsys.com

**Comment by beporter** [comment]
Basically unchecking **all** the boxes? Yeah, that's worth trying.

My goal is to make sure we explain (somewhere) how to generate the token, and which boxes (if any) must be checked in order for the token to work for this purpose. Make the process repeatable without having to do the research _every_ time.

**Comment by jtyost2** [comment]
Added to experiment with on a project.

**Comment by jtyost2** [comment]
No scope doesn't work.

I'm going to note it what the token is and what it's doing, what you can do if you don't want it, etc.
